import cv2
from pathlib import Path


# --------------------------------------------------
# Project paths
# --------------------------------------------------

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Oriented image generated by orientation.py
INPUT_PATH = PROJECT_ROOT / "output" / "oriented.jpeg"

# All generated images go into output/
OUTPUT_DIR = PROJECT_ROOT / "output"
OUTPUT_PATH = OUTPUT_DIR / "paper_boundary.png"

# Create output folder if it doesn't exist
OUTPUT_DIR.mkdir(exist_ok=True)


# --------------------------------------------------
# Read the oriented image
# --------------------------------------------------

img = cv2.imread(str(INPUT_PATH))

if img is None:
    raise FileNotFoundError(
        f"Could not read input image: {INPUT_PATH}"
    )


# --------------------------------------------------
# Convert to grayscale
# --------------------------------------------------

gray = cv2.cvtColor(
    img,
    cv2.COLOR_BGR2GRAY
)


# --------------------------------------------------
# Otsu thresholding
# --------------------------------------------------

_, thresh = cv2.threshold(
    gray,
    0,
    255,
    cv2.THRESH_BINARY + cv2.THRESH_OTSU
)


# --------------------------------------------------
# Find external contours
# --------------------------------------------------

contours, _ = cv2.findContours(
    thresh,
    cv2.RETR_EXTERNAL,
    cv2.CHAIN_APPROX_SIMPLE
)

if not contours:
    raise ValueError("No contours were detected.")


# --------------------------------------------------
# Find the largest contour
# --------------------------------------------------

largest_contour = max(
    contours,
    key=cv2.contourArea
)


# --------------------------------------------------
# Get its bounding rectangle
# --------------------------------------------------

x, y, w, h = cv2.boundingRect(
    largest_contour
)

print("Detected boundary:")
print("x =", x)
print("y =", y)
print("width =", w)
print("height =", h)


# --------------------------------------------------
# Crop the detected paper region
# --------------------------------------------------

cropped = img[
    y:y+h,
    x:x+w
]


# --------------------------------------------------
# Save result
# --------------------------------------------------

cv2.imwrite(
    str(OUTPUT_PATH),
    cropped
)

print("Paper boundary image saved as:", OUTPUT_PATH)


# --------------------------------------------------
# Display result
# --------------------------------------------------

cv2.imshow(
    "Paper Boundary",
    cropped
)

cv2.waitKey(0)
cv2.destroyAllWindows()